server:
  port: 8222

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/v1/employees/**
            - id: department-service
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/api/v1/departments/**
            - id: organization-service
              uri: lb://ORGANIZATION-SERVICE
              predicates:
                - Path=/api/v1/organizations/**
            - id: leave-service
              uri: lb://LEAVE-SERVICE
              predicates:
                - Path=/api/v1/leaves/**
            - id: timesheet-service
              uri: lb://TIMESHEET-SERVICE
              predicates:
                - Path=/api/v1/timesheets/**
            - id: payroll-service
              uri: lb://PAYROLL-SERVICE
              predicates:
                - Path=/api/v1/payrolls/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: hrms-rest-api
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8222/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://localhost:9098/realms/HRMS
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/HRMS"

keycloak:
  auth-server-url: http://localhost:9098
  realm: HRMS
  client-id: hrms-rest-api
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
