server:
  port: 8222

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/v1/employees/**
            - id: department-service
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/api/v1/departments/**
            - id: organization-service
              uri: lb://ORGANIZATION-SERVICE
              predicates:
                - Path=/api/v1/organizations/**
            - id: leave-service
              uri: lb://LEAVE-SERVICE
              predicates:
                - Path=/api/v1/leaves/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/HRMS"

keycloak:
  auth-server-url: http://localhost:9098
  realm: HRMS
  client-id: hrms-rest-api
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
